//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hazmat
{
    [Serializable]
    public class MecanumCmdMsg : Message
    {
        public const string k_RosMessageName = "hazmat_msgs/MecanumCmd";
        public override string RosMessageName => k_RosMessageName;

        public float front_right;
        public float front_left;
        public float rear_right;
        public float rear_left;

        public MecanumCmdMsg()
        {
            this.front_right = 0.0f;
            this.front_left = 0.0f;
            this.rear_right = 0.0f;
            this.rear_left = 0.0f;
        }

        public MecanumCmdMsg(float front_right, float front_left, float rear_right, float rear_left)
        {
            this.front_right = front_right;
            this.front_left = front_left;
            this.rear_right = rear_right;
            this.rear_left = rear_left;
        }

        public static MecanumCmdMsg Deserialize(MessageDeserializer deserializer) => new MecanumCmdMsg(deserializer);

        private MecanumCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.front_right);
            deserializer.Read(out this.front_left);
            deserializer.Read(out this.rear_right);
            deserializer.Read(out this.rear_left);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.front_right);
            serializer.Write(this.front_left);
            serializer.Write(this.rear_right);
            serializer.Write(this.rear_left);
        }

        public override string ToString()
        {
            return "MecanumCmdMsg: " +
            "\nfront_right: " + front_right.ToString() +
            "\nfront_left: " + front_left.ToString() +
            "\nrear_right: " + rear_right.ToString() +
            "\nrear_left: " + rear_left.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
